### ISSUE TITLE
Docs: Nexus 1.0 Memory Checking System

### ISSUE THREAD

**Issue by danielmarinq** [nexus-xyz/nexus-zkvm#110]
A full description of the size and architecture of the Nexus 1.0 Memory-Checking System

- [x] Explanation for the in-memory-expansion mechanism from the RISC-V translation
- [x] Concrete choice of parameters (leaf size, number of leafs, total memory size, arity of the memory tree, number of constraints)
- [x] A diagram for the system.

**Comment by michel-nexus** [comment]
[PR #123](https://github.com/nexus-xyz/nexus-zkvm/pull/123) addressed points 2 and 3.

**Comment by govereau** [comment]
Completed
