### ISSUE TITLE
Add allcontributors integration to README

### ISSUE THREAD

**Issue by govereau** [nexus-xyz/nexus-zkvm#117]
see: https://allcontributors.org

**Comment by slumber** [comment]
I'll just put my vote against it here.

We should value concise and informative README against questionable features that actually would take a lot of space with external 1-liners contributions.

Github already provides contributors statistics for those who are interested, I don't see any reason to copy it somewhere else.

**Comment by sjudson** [comment]
Testing...

@all-contributors please add @nexus-xyz

**Comment by sjudson** [comment]
@all-contributors please add @nexus-xyz for code

**Comment by slumber** [comment]
Completed https://github.com/nexus-xyz/nexus-zkvm/pull/122
