### ISSUE TITLE
Enable Curve + Commitment Configuration

### ISSUE THREAD

**Issue by sjudson** [nexus-xyz/nexus-zkvm#169]
At present, our proving scheme/compression implementations are written over generics. However, our vm is written over a specific curve pair [here](https://github.com/nexus-xyz/nexus-zkvm/blob/7fa6fe89ada8370f4a7f13cbaf96fb67e012dac1/vm/src/circuit/r1cs.rs#L16) and [here](https://github.com/nexus-xyz/nexus-zkvm/blob/7fa6fe89ada8370f4a7f13cbaf96fb67e012dac1/vm/src/memory/cacheline.rs#L5), while the `prover` crate (soon to be moved under the `api` crate) instantiates a particular set of choices for these generics:

- primary curve: `bn254`
- secondary curve: `grumpkin`
- commitment scheme: `PedersenCommitment`  
- polynomial commitment scheme: `Zeromorph`
- random oracle: `Poseidon`

In the future, the SDK will want to support user-configuration of these objects (with sensible defaults). So we should replace these concrete interfaces with generic ones all the way through, so that the SDK is not constrained to these particular choices.

**Comment by slumber** [comment]
I think it is up to discussion whether the end consumer crates should be generic.

**Comment by sjudson** [comment]
That's ultimately a UI/UX decision though. So though we may choose to limit how much configuration is exposed to the end-user, the `vm` arithmetization certainly shouldn't be curve-specific, while the `prover` crate needs to be uncoupled from the `tools` in order to feed both it + and the `sdk`, and in my opinion shouldn't overly constrain the options it presents to those interfaces.

**Comment by mx00s** [comment]
This sounds sensible to me.

Regarding whatever opinionated sets of generic arguments we pass in production contexts, whether the generic parameters exposed to users directly or not, it may be helpful to consider, "if I were to ask for a security audit, how would I specify the scope?"

**Comment by mx00s** [comment]
We may also find it makes sense to limit the number of generic parameters. Each additional generic parameter has a multiplicative effect on the set of generic type arguments to consider, and that can get complicated.

An alternative is to make a trait with associated types. You can then pass around sets of supported compositions of types as a single generic argument which is an implementation of that trait. So, to illustrate, something like:

```rust
trait Configuration {
    type PrimaryCurve;
    type SecondaryCurve;
    type CommitmentScheme;
    type PolynomialCommitmentScheme;
    type RandomOracle;

    ...
}

struct X;

impl Configuration for X {
    type PrimaryCurve = bn254;
    type SecondaryCurve = grumpkin;
    type CommitmentScheme = PedersenCommitment;
    type PolynomialCommitmentScheme = Zeromorph;
    type RandomOracle = Poseidon;
}

fn prove<C: Configuration>(config: &C, ...) -> ... {
    ...
}
```

Additionally, we may want to constrain those associated types with their own traits.

**Comment by sjudson** [comment]
Going to close this for now. Short term, our philosophy seems be settling on the `nexus-core` interface being opinionated with respect to these configurations, instead of allowing choice by the "consumer" (such as the SDK, CLI, or network crates). 

Even in the future if we decide to open up other configurations, this will most likely be done by enumerating a set of concrete choices, rather than exposing a generic interface.
