### ISSUE TITLE
Fix `[no_std]` `rust_analyzer` error for `cargo nexus new`

### ISSUE THREAD

**Issue by danielmarinq** [nexus-xyz/nexus-zkvm#18]
When creating a new Nexus project with `cargo nexus new`, rust analyzer shows the following error.

<img width="741" alt="Screenshot 2023-11-29 at 7 32 03 PM" src="https://github.com/nexus-xyz/nexus-zkvm/assets/60114322/9417bd1c-66a4-4453-bd59-86685e5a9058">

It should be fixable as described here: https://github.com/rust-lang/vscode-rust/issues/729#issuecomment-1102050361

**Comment by slumber** [comment]
Fixed in #195
