### ISSUE TITLE
/vm/src/circuit/r1cs.rs: fn store_reg : build constraints

### ISSUE THREAD

**Issue by hjlpb** [nexus-xyz/nexus-zkvm#200]
### Discussed in https://github.com/nexus-xyz/nexus-zkvm/discussions/199

<div type='discussions-op-text'>

<sup>Originally posted by **hjlpb** June 23, 2024</sup>
<img width="655" alt="image" src="https://github.com/nexus-xyz/nexus-zkvm/assets/20498177/7e3b869e-9b2a-4dfb-91c9-ea89b84e7262">
</div>

**Comment by yoichi-nexus** [comment]
I'll file a pull-request but it's @hjlpb 's catch.

**Comment by yoichi-nexus** [comment]
I'd like to encourage @hjlpb again to file the fix as the PR author.

**Comment by hjlpb** [comment]
ok, i will try. thanks.


| |
郝嘉禄
|
|
***@***.***
|


---- Replied Message ----
| From | Yoichi ***@***.***> |
| Date | 06/26/2024 22:19 |
| To | ***@***.***> |
| Cc | Jialu ***@***.***> ,
***@***.***> |
| Subject | Re: [nexus-xyz/nexus-zkvm] /vm/src/circuit/r1cs.rs: fn store_reg : build constraints (Issue #200) |

I'd like to encourage @hjlpb again to file the fix as the PR author.

**Comment by slumber** [comment]
Completed in https://github.com/nexus-xyz/nexus-zkvm/pull/205
