### ISSUE TITLE
[BUG]: test machines fail to prove with Nova

### ISSUE THREAD

**Issue by slumber** [nexus-xyz/nexus-zkvm#203]
### Program Information

Test machines
```js
"fib31", "bitop", "shift", "sub"
```

### Project Information

(old imports)
```rust
let public_params = nexus_prover::pp::gen_vm_pp(CONFIG.k, &())?;

// Run the program.
let vm_opts = VMOpts {
    k: CONFIG.k,
    machine: Some(String::from("fib31")),
    ..Default::default()
};
let trace = nexus_prover::run(
    &vm_opts,
    matches!(CONFIG.prover, ProverImpl::Nova(NovaImpl::Parallel)),
)?;

tracing::info!("Proving execution trace...");
let proof = nexus_prover::prove_seq(&public_params, trace)?;

tracing::info!("Verifying proof...");
proof.verify(&public_params, proof.step_num() as _)?;
```

### Reproduction Steps

run the code

### What is expected?

Proof is valid

### What is actually happening?

Proof is invalid

### Any additional comments?

Probably related to transition from NexusVM instructions encoding back to RISCV

**Comment by zkp72345** [comment]
To add more context, I bumped to [c470d63](https://github.com/nexus-xyz/nexus-zkvm/commit/c470d637134797162546321140dbb213dd1761a2) and retested these with hypernova. For `k=1` only `"ldst"` failed, but `"fib31"`, `"bitop"`, `"ldst"`, `"shift"`, and `"sub"` each failed to verify for `k=16`.

**Comment by slumber** [comment]
Fixed by https://github.com/nexus-xyz/nexus-zkvm/pull/214
Credited to @yoichi-nexus
