### ISSUE TITLE
upgrade to arkworks 0.5.0

### ISSUE THREAD

**Issue by slumber** [nexus-xyz/nexus-zkvm#212]
`ark-*` crates are published with `0.5.0-alpha` tag. Once it's made stable, we can upgrade and remove [patches] section from the Cargo.toml.

Will require some changes, at least due to interfaces being renamed.

**Comment by mahmudsudo** [comment]
hi, can i take on this issue ?

**Comment by slumber** [comment]
0.5 is not stable yet, and `ark_poly_commit` hasn't got any upgrade, so the issue is blocked.
