### ISSUE TITLE
[BUG]: docs/README.md mentions npm while it is not supposed to

### ISSUE THREAD

**Issue by yoichi-nexus** [nexus-xyz/nexus-zkvm#227]
### Program Information

Not relevant. This issue is about documentation.

### Project Information

Maintaining documentation of Nexus zkVM.

### Reproduction Steps

open docs/README.md

### What is expected?

yarn instead of npm should be mentioned https://github.com/nexus-xyz/nexus-zkvm/pull/216#discussion_r1679521334

### What is actually happening?

npm is mentioned.

**Comment by SVell** [comment]
Fixed in https://github.com/nexus-xyz/nexus-docs/pull/10
