### ISSUE TITLE
[BUG]: CI doesn't catch compilation error in runtime/src

### ISSUE THREAD

**Issue by yoichi-nexus** [nexus-xyz/nexus-zkvm#230]
### Program Information

not specific to any zkVM program

### Project Information

maintaining the nexus-zkvm project.

### Reproduction Steps

revert https://github.com/nexus-xyz/nexus-zkvm/pull/229/files and create a PR.

### What is expected?

CI should catch compilation errors for nonexistent variables and names.

### What is actually happening?

CI succeeds.

**Comment by slumber** [comment]
Fixed in https://github.com/nexus-xyz/nexus-zkvm/pull/231
