### ISSUE TITLE
Re-export `postcard` from `nexus-runtime` to `nexus-sdk`

### ISSUE THREAD

**Issue by duc-nx** [nexus-xyz/nexus-zkvm#277]
### What is the problem?
At the moment, in SDK, the host will have to add postcard in #276 . 
When user modify/update the `postcard` crate, it is not guarantee to work. 

We have a problem with Rust 1.80.1 and `postcard = 1.0.9`, thus, by forcing `postcard` in `nexus-runtime` and re-export in `SDK` a robust solution than the current approach.

**Comment by sjudson** [comment]
I think a decent move would be to re-export `postcard` through the runtime now and update the docs + examples to use it, but then leave the `cargo nexus host` command as is for a while to not break any one currently depending on examples where `postcard` is installed directly into the guest package.
