### ISSUE TITLE
[BUG]: cant find TAG V0.2.3

### ISSUE THREAD

**Issue by zhangmo235** [nexus-xyz/nexus-zkvm#286]
### Program Information

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

### Project Information

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

### Reproduction Steps

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

### What is expected?

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

### What is actually happening?

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

### System Information

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

### Any additional comments?

Updating git repository `https://github.com/nexus-xyz/nexus-zkvm`
error: failed to find tag `'v0.2.3'`

Caused by:
  reference 'refs/remotes/origin/tags/'v0.2.3'' not found; class=Reference (4); code=NotFound (-3)

**Comment by sjudson** [comment]
A new release, `v0.2.4` was just cut. I'll close this for now, but feel free to reopen a new issue if the problem persists.
