### ISSUE TITLE
[FEATURE]: Does nexus support running SHA256?

### ISSUE THREAD

**Issue by MuhtasimTanmoy** [nexus-xyz/nexus-zkvm#290]
### What is the problem?
I am trying to run SHA256, getting error.

### What do you want to happen?
Run and generate proof correctly.

### Existing alternatives
N/A.

### Additional notes
N/A.

**Comment by sjudson** [comment]
Yes we should be able to execute and prove a SHA256 program. Can you file a bug report (rather than feature request) and fill out the questions contained within the template? That'll help us investigate the cause of the error you're seeing.
