### ISSUE TITLE
Feedback for “Nexus Network CLI”

### ISSUE THREAD

**Issue by solotop999** [nexus-xyz/nexus-zkvm#299]
> curl https://cli.nexus.xyz/ | sh
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  2306  100  2306    0     0  14929      0 --:--:-- --:--:-- --:--:-- 14974
> rustc 1.83.0 (90b35a623 2024-11-26)
> Do you agree to the Nexus Beta Terms of Use (https://nexus.xyz/terms-of-use)? (Y/n)
> /root/.nexus/network-api exists. Updating.
> No local changes to save
> HEAD is now at cfacdc1 fix: CLI analytics fix (#101)
>    Compiling ark-poly v0.4.2 (https://github.com/arkworks-rs/algebra/?rev=2a80c54#2a80c546)
>    Compiling ark-relations v0.4.0
>    Compiling zstd-sys v2.0.13+zstd.1.5.6 (https://github.com/gyscos/zstd-rs#59e1da7f)
>    Compiling hyper v1.4.1
>    Compiling zstd-safe v6.0.6
>    Compiling zstd-safe v7.2.1 (https://github.com/gyscos/zstd-rs#59e1da7f)
>    Compiling futures v0.3.30
>    Compiling tracing-subscriber v0.3.18
>    Compiling tokio-tungstenite v0.23.1
>    Compiling random_word v0.4.3
>    Compiling nexus-network v0.4.0 (/root/.nexus/network-api/clients/cli)
>    Compiling dirs v5.0.1
>    Compiling prost v0.13.1
>    Compiling uuid v1.10.0
>    Compiling md5 v0.7.0
>    Compiling home v0.5.9
>    Compiling jsonrpsee v0.23.2
> The following warnings were emitted during compilation:
> 
> **warning: nexus-network@0.4.0: Failed to run protoc: No such file or directory (os error 2)**
> 
> error: failed to run custom build command for nexus-network v0.4.0 (/root/.nexus/network-api/clients/cli)
> 
> Caused by:
>   process didn't exit successfully: /root/.nexus/network-api/clients/cli/target/release/build/nexus-network-01d0541f667d1829/build-script-build (exit status: 1)
>   --- stdout
>   cargo:warning=Failed to run protoc: No such file or directory (os error 2)
> 
>   --- stderr
>   Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> warning: build failed, waiting for other jobs to finish...
> 

**FIX:**
```
sudo apt install -y protobuf-compiler
export PATH=$PATH:/path/to/protoc/bin
```

**Comment by qdriven** [comment]
works for me too. In Mac, ```brew install protobuff```
