### ISSUE TITLE
Mismatch in Local and Network Cycles Displayed

### ISSUE THREAD

**Issue by Professor-Chen** [nexus-xyz/nexus-zkvm#319]
Description:
I noticed a discrepancy between the cycles displayed locally and the ones reported on the Nexus network dashboard. Specifically:

Locally, the client shows 9.84K cycles, while the network dashboard only reports 720 cycles under "Nexus Points".

Both metrics are labeled as "cycles," which adds to the confusion about what they actually represent.

Questions/Concerns:

Does the 720 cycles refer to verified contributions, while 9.84K cycles represent the raw number of cycles processed locally?

Is there a delay or validation step in syncing local cycles with the network?

Are some tasks being rejected or excluded from the Nexus Points system, and if so, why?

Steps to Reproduce:

Run the Nexus prover client locally.

Monitor the "cycles" displayed in the local terminal output.

Compare the local cycles with the cycles shown in the Nexus network dashboard under "Nexus Points."

Expected Behavior:

Clear alignment or explanation of the difference between local cycles and network-reported cycles.

Consistency in labeling or documentation explaining how these values are calculated.

Observed Behavior:

Local cycles significantly exceed the Nexus Points cycles, with no clear indication of what causes the difference.

Environment:

Prover Client Version: [Insert Version]

OS: [Insert OS and Version, e.g., Ubuntu 20.04]

Network: [Testnet/Mainnet]

Additional Context:
This discrepancy makes it difficult to understand the actual contribution to the network and how points are accumulated. Clarification or documentation on the calculation and syncing process would be greatly appreciated.

Thank you for looking into this issue!

**Comment by sjudson** [comment]
Redirect to https://github.com/nexus-xyz/network-api or our social channels.
