### ISSUE TITLE
Add MIT / Apache 2.0 License

### ISSUE THREAD

**Issue by danielmarinq** [nexus-xyz/nexus-zkvm#91]

**Comment by danielmarinq** [comment]
Also add license info on README

**Comment by govereau** [comment]
Do you mean something specific, or jut add a sentence to the README about the license?

**Comment by danielmarinq** [comment]
Specific, as most other projects

**Comment by govereau** [comment]
Ok, I think I know what you mean. I will interpret "most" to mean things like tokio, and not, say, Linux.
Check if this is what you want.
