### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by danielmarinq** [nexus-xyz/nexus-zkvm#95]
Something similar to [nextjs](https://github.com/vercel/next.js/blob/canary/contributing.md), [reth](https://github.com/paradigmxyz/reth/blob/main/CONTRIBUTING.md)  or [tokio](https://github.com/tokio-rs/tokio/blob/master/CONTRIBUTING.md).

**Comment by sjudson** [comment]
Resolved by https://github.com/nexus-xyz/nexus-zkvm/pull/96.
